export const VERTICALS = {
  finance: {
    value: 'finance',
    label: 'Finance',
  },
  retail: {
    value: 'retail',
    label: 'Retail',
  },
  support: {
    value: 'support',
    label: 'Support',
  },
  helpdesk: {
    value: 'helpdesk',
    label: 'Helpdesk',
  },
  telecommunications: {
    value: 'telecommunications',
    label: 'Telecommunications',
  },
  healthcare: {
    value: 'healthcare',
    label: 'Healthcare',
  },
  ecommerce: {
    value: 'ecommerce',
    label: 'E-commerce',
  },
};

export const INTENT_SUGGESTIONS_CATEGORIES = [
  {
    tag: 'account',
    label: 'Account',
    children: [
      { tag: 'activation', label: 'Account activation' },
      { tag: 'data_restrictions', label: 'Account data restrictions' },
      { tag: 'documentation', label: 'Account documentation' },
      { tag: 'fake', label: 'Fake accounts' },
      { tag: 'flagged', label: 'Account flagged' },
      { tag: 'info', label: 'Account information' },
      { tag: 'invitation', label: 'Account invitation' },
      { tag: 'manager', label: 'Manager' },
      { tag: 'new', label: 'New account' },
      { tag: 'recovery', label: 'Account recovery' },
      { tag: 'status', label: 'Account status' },
      { tag: 'update', label: 'Account update' },
      { tag: 'verification', label: 'Account verification' },
    ],
  },
  {
    tag: 'billing',
    label: 'Billing',
    children: [
      { tag: 'agreement', label: 'Billing agreement' },
      { tag: 'balance', label: 'Balance' },
      { tag: 'checkout', label: 'Billing checkout' },
      { tag: 'credit_info', label: 'Credit information' },
      { tag: 'credit_note', label: 'Credit note' },
      { tag: 'discount', label: 'Discount' },
      { tag: 'documentation', label: 'Billing documentation' },
      { tag: 'expenses', label: 'Expenses' },
      { tag: 'invoice', label: 'Invoice' },
      { tag: 'loyalty_card', label: 'Loyalty card' },
      { tag: 'multiple_users', label: 'Multiple users' },
      { tag: 'payment_change', label: 'Payment change' },
      { tag: 'payment_info', label: 'Payment information' },
      { tag: 'price_clarification', label: 'Price clarification' },
      { tag: 'price_feedback', label: 'Price feedback' },
      { tag: 'refund', label: 'Refund' },
      { tag: 'request_pay', label: 'Request to pay' },
      { tag: 'selling', label: 'Selling' },
      { tag: 'subscription_cancel', label: 'Subscription cancel' },
      { tag: 'subscription_issue', label: 'Subscription issue' },
      { tag: 'subscription_status', label: 'Subscription status' },
      { tag: 'subscription_transfer', label: 'Subscription transfer' },
      { tag: 'subscription_update', label: 'Subscription update' },
      { tag: 'tax_info', label: 'Tax information' },
      { tag: 'tip', label: 'Tip' },
      { tag: 'trial', label: 'Trial' },
      { tag: 'wrong', label: 'Wrong charge' },
    ],
  },
  {
    tag: 'finance',
    label: 'Finance',
    children: [
      { tag: 'credit_cancellation', label: 'Credit cancellation' },
      { tag: 'credit_new', label: 'Credit new' },
      { tag: 'credit_offer', label: 'Credit offer' },
      { tag: 'fees_info', label: 'Fees information' },
      { tag: 'interest', label: 'Interest' },
      { tag: 'transaction_cancel', label: 'Transaction cancel' },
      { tag: 'transaction_status', label: 'Transaction status' },
      { tag: 'unauthorized_use', label: 'Unauthorized use' },
    ],
  },
  {
    tag: 'hardware',
    label: 'Hardware',
    children: [
      { tag: 'device', label: 'Hardware device' },
      { tag: 'peripheral_device', label: 'Hardware peripheral device' },
    ],
  },
  {
    tag: 'human_resources',
    label: 'Human resources',
    children: [
      { tag: 'employment_status_update', label: 'Employment status update' },
      { tag: 'leave_policy_info', label: 'Leave policy information' },
      { tag: 'recruitment', label: 'Human resources recruitment' },
    ],
  },
  {
    tag: 'insurance',
    label: 'Insurance',
    children: [
      { tag: 'claim', label: 'Claim' },
      { tag: 'policy_cancel', label: 'Policy cancel' },
      { tag: 'policy_update', label: 'Policy update' },
    ],
  },
  {
    tag: 'misc',
    label: 'Misc',
    children: [
      { tag: 'attachment_missing', label: 'Attachment missing' },
      { tag: 'communication', label: 'Communications' },
      { tag: 'contact', label: 'Contact' },
      { tag: 'do_not_send', label: "Don't send documentation" },
      { tag: 'email_management', label: 'Email management' },
      { tag: 'feedback', label: 'Feedback' },
      { tag: 'handle', label: 'Handle' },
      { tag: 'image', label: 'Image' },
      { tag: 'intellectual_property', label: 'Intellectual property' },
      { tag: 'job_application', label: 'Job application' },
      { tag: 'not_received', label: 'Unable to receive message' },
      { tag: 'previous_message', label: 'Previous message' },
      { tag: 'promotional_campaign', label: 'Promotional campaign' },
      { tag: 'query_status', label: 'Query status' },
      { tag: 'received', label: 'Received message' },
      { tag: 'send', label: 'Send request' },
      { tag: 'thanks', label: 'Thanks' },
      { tag: 'unsolicited', label: 'Unsolicited' },
      { tag: 'video', label: 'Video' },
    ],
  },
  {
    tag: 'network',
    label: 'Network',
    children: [{ tag: 'connection', label: 'Connectivity' }],
  },
  {
    tag: 'order',
    label: 'Order',
    children: [
      { tag: 'availability', label: 'Order availability' },
      { tag: 'cancellation', label: 'Order cancelation' },
      { tag: 'collect', label: 'Order collection' },
      { tag: 'customs_clearance', label: 'Customs clearance' },
      { tag: 'delivery_info', label: 'Delivery information' },
      { tag: 'documentation', label: 'Order documentation' },
      { tag: 'fulfilment', label: 'Order fulfilment' },
      { tag: 'new', label: 'Place new order' },
      { tag: 'notifications', label: 'Order notifications' },
      { tag: 'not_delivered', label: 'Order not delivered' },
      { tag: 'product_choice', label: 'Product choice' },
      { tag: 'product_details', label: 'Product details' },
      { tag: 'product_documentation', label: 'Product documentation' },
      { tag: 'product_issue', label: 'Product issue' },
      { tag: 'product_usage', label: 'Product usage' },
      { tag: 'return', label: 'Order return' },
      { tag: 'return_notifications', label: 'Order return notifications' },
      { tag: 'shipping_info', label: 'Shipping information' },
      { tag: 'status', label: 'Order status' },
      { tag: 'update', label: 'Order update' },
      { tag: 'warranty', label: 'Warranty' },
      { tag: 'warranty_form', label: 'Warranty form' },
      { tag: 'wrong_delivery', label: 'Wrong delivery' },
      { tag: 'wrong_product', label: 'Wrong product' },
    ],
  },
  {
    tag: 'sell',
    label: 'Sell',
    children: [
      { tag: 'info', label: 'Sales information' },
      { tag: 'issue', label: 'Sales issue' },
      { tag: 'notifications', label: 'Sales notification' },
      { tag: 'status', label: 'Sales status' },
      { tag: 'update', label: 'Sales update' },
    ],
  },
  {
    tag: 'service',
    label: 'Service',
    children: [
      { tag: 'appointment', label: 'Appointment' },
      { tag: 'info', label: 'Service information' },
      { tag: 'update', label: 'Service update' },
    ],
  },
  {
    tag: 'software',
    label: 'Software',
    children: [
      { tag: 'api', label: 'API' },
      { tag: 'compatibility', label: 'Software compatibility' },
      { tag: 'connection', label: 'Software connection' },
      { tag: 'crash', label: 'Software crash' },
      { tag: 'data', label: 'Software data' },
      { tag: 'feature_feedback', label: 'Feature feedback' },
      { tag: 'feature_missing', label: 'Feature missing' },
      { tag: 'info', label: 'Software information' },
      { tag: 'install', label: 'Install' },
      { tag: 'issue_generic', label: 'Generic error' },
      { tag: 'login_config', label: 'Login configuration' },
      { tag: 'login_issues', label: 'Login issues' },
      { tag: 'notifications', label: 'Notifications' },
      { tag: 'open', label: 'Launch' },
      { tag: 'pairing', label: 'Pairing' },
      { tag: 'performance', label: 'Performance' },
      { tag: 'recording_issue', label: 'Recording issue' },
      { tag: 'seats', label: 'Seats management' },
      { tag: 'sync', label: 'Synchronization' },
      { tag: 'transfer', label: 'Transfer data' },
      { tag: 'uninstall', label: 'Uninstall' },
      { tag: 'update', label: 'Software update' },
      { tag: 'verification_code', label: 'Software verification code' },
      { tag: 'vpn', label: 'VPN' },
    ],
  },
  {
    tag: 'travel',
    label: 'Travel',
    children: [
      { tag: 'booking_cancellation', label: 'Booking cancellation' },
      { tag: 'booking_issue', label: 'Booking issue' },
      { tag: 'booking_new', label: 'Booking new' },
      { tag: 'booking_status', label: 'Booking status' },
      { tag: 'booking_update', label: 'Booking update' },
      { tag: 'service_issue', label: 'Service issue' },
    ],
  },
  {
    tag: 'workplace',
    label: 'Workplace',
    children: [{ tag: 'maintenance', label: 'Maintenance' }],
  },
];
